const SUPABASE_URL="https://itoxohdbwcxmrlxqfkct.supabase.co";
const SUPABASE_KEY="sb_publishable_Enj8kwWvvtHNUCBva-uPHg_incNY4jK";
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
const PIX_KEY="brasilsuvivalzbrasilsuvivalz@gmail.com",PIX_NAME="GUSTAVO DE PAULA BARBOSA",PIX_CITY="RIO BRANCO";
const $=id=>document.getElementById(id);
const DATA={items:[
{id:"nails",name:"Caixa de Pregos",tag:"CONSTRUÇÃO VANILLA",img:"nails.jpg",brl:2,bs:650},{id:"wire",name:"Arame x2",tag:"CONSTRUÇÃO VANILLA",img:"wire.jpg",brl:5,bs:820},{id:"hammer",name:"Martelo",tag:"FERRAMENTA",img:"hammer.jpg",brl:2,bs:550},{id:"hatchet",name:"Machado Pequeno",tag:"FERRAMENTA",img:"hatchet.jpg",brl:6,bs:1200},{id:"saw",name:"Serrote",tag:"FERRAMENTA",img:"handsaw.jpg",brl:6,bs:850},{id:"stone",name:"Pedra de Amolar",tag:"FERRAMENTA",img:"sharpening_stone.jpg",brl:3,bs:800},{id:"planks",name:"Pack 10 Tábuas",tag:"CONSTRUÇÃO VANILLA",img:"planks.jpg",brl:2,bs:800},{id:"codelock",name:"CodeLock",tag:"SEGURANÇA",img:"codlock.jpg",brl:15,bs:1120}],
cars:[{id:"sarka",name:"Sarka 120",tag:"VEÍCULO VANILLA",img:"sarka.jpg",brl:25,bs:7000},{id:"olga",name:"Olga 24",tag:"VEÍCULO VANILLA",img:"olga.jpg",brl:25,bs:5000},{id:"gunter",name:"Gunter 2",tag:"VEÍCULO VANILLA",img:"gunter.jpg",brl:25,bs:7000},{id:"ada",name:"Ada 4x4",tag:"VEÍCULO VANILLA",img:"ada.jpg",brl:25,bs:9800},{id:"m3s",name:"caminhão",tag:"VEÍCULO VANILLA",img:"m3s.jpg",brl:70,bs:12000}],
kits:[{id:"kitbase",name:"Kit Base — 20 itens",tag:"KIT DE CONSTRUÇÃO",img:"kit_base.jpg",brl:25,bs:1200,desc:"Para começar sua base.",items:["3x Caixa de Pregos","2x Martelo","2x Serrote","2x Machado Pequeno","6x Pedra de Amolar","50x Tábuas","50x Madeira","1x Corda"]},{id:"kitmedio",name:"Kit Médio — 30 itens",tag:"KIT DE CONSTRUÇÃO",img:"kit_medio.jpg",brl:55,bs:10000,desc:"Mais recursos para expansão.",items:["5x Caixa de Pregos","3x Martelo","3x Serrote","3x Machado Pequeno","10x Pedra de Amolar","100x Tábuas","100x Madeira","2x Cordas"]},{id:"kitavancado",name:"Kit Avançado — 50 itens",tag:"KIT DE CONSTRUÇÃO",img:"kit_avancado.jpg",brl:100,bs:15000,desc:"Pacote grande para base fortificada.",items:["8x Caixa de Pregos","5x Martelo","4x Serrote","4x Machado Pequeno","15x Pedra de Amolar","200x Tábuas","200x Madeira","4x Cordas"]}],
vip:[{id:"vip30",name:"VIP Prioridade — 30 dias",tag:"VIP",img:"vip.jpg",brl:35,bs:15000,desc:"Tenha prioridade na fila de entrada e acesse o servidor mais rápido nos horários de maior movimento. O VIP é ideal para quem joga com frequência e também ajuda a manter o BRASIL SURVIVALZ ativo e em constante evolução."}],
mmg:[
{id:"gunrackblue",name:"Gun Rack Blue",tag:"MMG STORAGE",img:"mmg_gun_rack_blue.jpg",brl:35,bs:3500,desc:"8 slot arma"},
{id:"ta50blue",name:"ARMARIO",tag:"MMG STORAGE",img:"mmg_ta50_locker_blue.jpg",brl:35,bs:4600,desc:"100 slots de armazenamento, além de espaços próprios para 5 armas, 2 caixas de munição, 1 pistola e loadout. Ele também é lockable."},
{id:"gunwallwooden",name:"painel de armas",tag:"MMG STORAGE",img:"mmg_gun_wall_wooden.jpg",brl:45,bs:5000,desc:"40 slots de armazenamento + suporte para 8 armas."},
{id:"gunwallmetal",name:"PAINEL DE ARMAS",tag:"MMG STORAGE",img:"mmg_gun_wall_metal.jpg",brl:35,bs:4300,desc:"40 slots + suporte para 8 armas"},
{id:"palette500",name:"BAU COM 500 slots",tag:"MMG STORAGE • 500 SLOTS",img:"mmg_palette_storage_500.jpg",brl:40,bs:12000,desc:"500 slots • 500 slots"}
]};
const COIN_PACKAGES=[
{id:"bs1500",coins:1500,brl:15},
{id:"bs2600",coins:2600,brl:20},
{id:"bs3600",coins:3600,brl:25},
{id:"bs4600",coins:4600,brl:40},
{id:"bs8600",coins:8600,brl:80,featured:true}
];
const all=[...DATA.items,...DATA.cars,...DATA.kits,...DATA.vip,...DATA.mmg];let cart=[];try{cart=JSON.parse(localStorage.getItem("bsz_cart_v10_1")||"[]")}catch{}
const brl=n=>n==null?"—":n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"}),bs=n=>`${Number(n||0).toLocaleString("pt-BR")} BS`;
function card(p,extra=""){const kit=p.items?`<div class="kitList">${p.items.map(x=>`<div>• ${x}</div>`).join("")}</div>`:"";return `<article class="product ${extra}"><div class="productImg"><img src="${p.img}" alt="${p.name}" loading="lazy" onerror="this.style.display='none'"></div><div class="productBody"><div class="tag">${p.tag}</div><h3>${p.name}</h3><div class="desc">${p.desc||""}</div>${kit}<div class="prices"><div class="price"><small>PIX</small><b>${brl(p.brl)}</b></div><div class="price bs"><small>BS COINS</small><b>${bs(p.bs)}</b></div></div><button data-add="${p.id}">🛒 ADICIONAR</button></div></article>`}
function render(){[["itemProducts",DATA.items],["carProducts",DATA.cars],["kitProducts",DATA.kits],["vipProducts",DATA.vip],["mmgProducts",DATA.mmg]].forEach(([id,data])=>$(id).innerHTML=data.map(p=>card(p,id==="vipProducts"?"vipCard":"")).join(""));document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>add(b.dataset.add));const cp=$("coinPackages");if(cp){cp.innerHTML=COIN_PACKAGES.map(p=>`<article class="coinPack ${p.featured?'featured':''}">${p.featured?'<span class="coinPackBadge">MAIOR PACOTE</span>':''}<div class="coinArt">BS</div><strong>${p.coins.toLocaleString('pt-BR')}<span>BS COINS</span></strong><div class="coinPrice">${brl(p.brl)}</div><small>COMPRA SOMENTE VIA PIX</small><button data-buy-coins="${p.id}">◆ COMPRAR COM PIX</button></article>`).join('');document.querySelectorAll('[data-buy-coins]').forEach(b=>b.onclick=()=>buyCoinPack(b.dataset.buyCoins))}drawCart()}
function add(id){const r=cart.find(x=>x.id===id);r?r.qty++:cart.push({id,qty:1});saveCart();openDrawer()}function change(id,d){const r=cart.find(x=>x.id===id);if(!r)return;r.qty+=d;if(r.qty<=0)cart=cart.filter(x=>x.id!==id);saveCart()}function saveCart(){localStorage.setItem("bsz_cart_v10_1",JSON.stringify(cart));drawCart()}
function totals(){let totalBRL=0,totalBS=0;cart.forEach(r=>{const p=all.find(x=>x.id===r.id);if(!p)return;if(p.brl!=null)totalBRL+=p.brl*r.qty;totalBS+=p.bs*r.qty});return{totalBRL,totalBS}}
function drawCart(){const count=cart.reduce((s,x)=>s+x.qty,0);$("cartCount").textContent=count;$("cartEmpty").style.display=count?"none":"block";$("sideCartText").textContent=count?`${count} item(ns) no carrinho.`:"Seu carrinho está vazio.";$("cartItems").innerHTML=cart.map(r=>{const p=all.find(x=>x.id===r.id);return p?`<div class="cartRow"><div><b>${p.name}</b><small>${p.brl!=null?brl(p.brl*r.qty)+" • ":""}${bs(p.bs*r.qty)}</small></div><div class="qty"><button data-dec="${p.id}">−</button><span>${r.qty}</span><button data-inc="${p.id}">+</button></div></div>`:""}).join("");document.querySelectorAll("[data-dec]").forEach(b=>b.onclick=()=>change(b.dataset.dec,-1));document.querySelectorAll("[data-inc]").forEach(b=>b.onclick=()=>change(b.dataset.inc,1));const t=totals();$("totalBRL").textContent=brl(t.totalBRL);$("totalBS").textContent=bs(t.totalBS)}
function openDrawer(){$("cartDrawer").classList.add("open");$("drawerBackdrop").classList.add("show")}function closeDrawer(){$("cartDrawer").classList.remove("open");$("drawerBackdrop").classList.remove("show")}
$("openCart").onclick=$("sideCartBtn").onclick=openDrawer;$("closeCart").onclick=$("drawerBackdrop").onclick=closeDrawer;$("clearCart").onclick=()=>{cart=[];saveCart()};
function validSteam(v){return /^7656119\d{10}$/.test(String(v).trim())}function bindSteam(inp,status){inp.addEventListener("input",()=>{inp.value=inp.value.replace(/\D/g,"").slice(0,17);const n=inp.value.length;if(!n){status.className="status";status.textContent="Digite exatamente 17 números."}else if(validSteam(inp.value)){status.className="status ok";status.textContent="✓ SteamID64 válido (17/17)."}else{status.className="status bad";status.textContent=n<17?`Faltam ${17-n} número(s) — ${n}/17`:`SteamID64 inválido. Deve começar com 7656119.`}})}bindSteam($("regSteam"),$("regSteamStatus"));bindSteam($("steamId"),$("checkoutSteamStatus"));
function show(id){$(id).classList.add("show")}function hide(id){$(id).classList.remove("show")}document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>hide(b.dataset.close));function message(t,b){$("messageTitle").textContent=t;$("messageBody").textContent=b;show("messageModal")}
function openAuth(){show("authModal");refreshAccountUI()}$("openAccount").onclick=$("sideLogin").onclick=$("sideAccount").onclick=$("coinsAccountBtn").onclick=openAuth;document.querySelectorAll("[data-auth]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-auth]").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("loginForm").classList.toggle("hidden",b.dataset.auth!=="login");$("registerForm").classList.toggle("hidden",b.dataset.auth!=="register");$("accountPanel").classList.add("hidden")});
async function getProfile(uid){if(!sb)return null;const{data,error}=await sb.from("profiles").select("user_id,player_name,steam_id,bs_coins,avatar_url,is_admin").eq("user_id",uid).maybeSingle();if(error)throw error;return data}
async function refreshAccountUI(){if(!sb)return;const{data:{session}}=await sb.auth.getSession();if(!session){$("accountPanel").classList.add("hidden");$("loginForm").classList.remove("hidden");$("sideLoggedOut").classList.remove("hidden");$("sideLoggedIn").classList.add("hidden");$("adminInsideBtn")?.classList.add("hidden");$("topAvatar")?.classList.add("hidden");return}try{const p=await getProfile(session.user.id);$("loginForm").classList.add("hidden");$("registerForm").classList.add("hidden");$("accountPanel").classList.remove("hidden");$("accountName").textContent=p?.player_name||session.user.email;$("accountSteam").textContent=p?.steam_id||"Não informado";$("accountBalance").textContent=bs(p?.bs_coins||0);$("sideBalance").textContent=bs(p?.bs_coins||0);$("sidePlayer").textContent=p?.player_name||session.user.email;$("sideLoggedOut").classList.add("hidden");$("sideLoggedIn").classList.remove("hidden");if(p?.player_name)$("playerName").value=p.player_name;if(p?.steam_id)$("steamId").value=p.steam_id;const avatar=p?.avatar_url;if(avatar){$("accountAvatarImg").src=avatar;$("accountAvatarImg").classList.remove("hidden");$("avatarFallback").classList.add("hidden");$("topAvatar").src=avatar;$("topAvatar").classList.remove("hidden")}else{$("accountAvatarImg").classList.add("hidden");$("avatarFallback").classList.remove("hidden");$("topAvatar").classList.add("hidden")}$("adminInsideBtn")?.classList.toggle("hidden",p?.is_admin!==true)}catch(e){message("Erro ao carregar conta",e.message)}}
async function syncSteamAvatar(){if(!sb)return;const{data:{session}}=await sb.auth.getSession();if(!session)return openAuth();const p=await getProfile(session.user.id);if(!p?.steam_id)return message("SteamID64 necessário","Cadastre seu SteamID64 primeiro.");const{data,error}=await sb.functions.invoke("steam-avatar",{body:{steam_id:p.steam_id}});if(error)return message("Foto da Steam","A função steam-avatar ainda não está configurada no Supabase ou ocorreu um erro.");if(!data?.avatar_url)return message("Foto da Steam","Não foi possível encontrar um avatar público para esse SteamID64.");await refreshAccountUI();message("Foto atualizada","Avatar da Steam atualizado com sucesso.")}
$("syncSteamAvatar").onclick=syncSteamAvatar;
$("registerForm").onsubmit=async e=>{e.preventDefault();if(!sb)return message("Supabase indisponível","A biblioteca não carregou.");const player=$("regPlayer").value.trim(),steam=$("regSteam").value.trim(),email=$("regEmail").value.trim().toLowerCase(),pw=$("regPassword").value;if(!player)return message("Nome obrigatório","Informe o nome usado no DayZ.");if(!validSteam(steam))return message("SteamID64 inválido","Use exatamente 17 números e confirme seu SteamID64.");if(pw.length<6)return message("Senha curta","Use pelo menos 6 caracteres.");if(pw!==$("regConfirm").value)return message("Senhas diferentes","A confirmação precisa ser igual à senha.");const{error}=await sb.auth.signUp({email,password:pw,options:{data:{player_name:player,steam_id:steam}}});if(error)return message("Erro no cadastro",error.message);message("Conta criada","Cadastro concluído. Confira seu e-mail se a confirmação estiver ativada e depois entre na conta.");setTimeout(refreshAccountUI,500)};
$("loginForm").onsubmit=async e=>{e.preventDefault();if(!sb)return;const{error}=await sb.auth.signInWithPassword({email:$("loginEmail").value.trim().toLowerCase(),password:$("loginPassword").value});if(error)return message("Não foi possível entrar","Confira e-mail e senha.");await refreshAccountUI();hide("authModal")};$("logoutBtn").onclick=async()=>{await sb.auth.signOut();await refreshAccountUI()};if(sb)sb.auth.onAuthStateChange(()=>setTimeout(refreshAccountUI,0));
function f(id,v){return id+String(v.length).padStart(2,"0")+v}function crc(s){let c=0xffff;for(let x=0;x<s.length;x++){c^=s.charCodeAt(x)<<8;for(let i=0;i<8;i++)c=(c&0x8000)?((c<<1)^0x1021):(c<<1),c&=0xffff}return c.toString(16).toUpperCase().padStart(4,"0")}function clean(s,m){return s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^A-Z0-9 .-]/gi,"").toUpperCase().slice(0,m)}function pixPayload(a,tx){const mai=f("26",f("00","BR.GOV.BCB.PIX")+f("01",PIX_KEY)),add=f("62",f("05",tx));let p=f("00","01")+mai+f("52","0000")+f("53","986")+f("54",a.toFixed(2))+f("58","BR")+f("59",clean(PIX_NAME,25))+f("60",clean(PIX_CITY,15))+add+"6304";return p+crc(p)}
$("checkoutPix").onclick=()=>{if(!cart.length)return message("Carrinho vazio","Adicione produtos primeiro.");closeDrawer();show("checkoutModal")};$("makePix").onclick=()=>{const t=totals(),name=$("playerName").value.trim(),sid=$("steamId").value.trim();if(!name)return message("Nome obrigatório","Informe seu nome no DayZ.");if(!validSteam(sid))return message("SteamID64 inválido","Digite exatamente 17 números.");if(t.totalBRL<=0)return message("Somente BS Coins","Este carrinho não possui valor em PIX.");const tx=("BSZ"+Date.now().toString().slice(-12)).slice(0,25),code=pixPayload(t.totalBRL,tx);$("pixArea").classList.remove("hidden");$("pixCode").value=code;$("pixAmount").textContent=`PIX ${brl(t.totalBRL)} • ${tx}`;$("qrcode").innerHTML="";if(window.QRCode)new QRCode($("qrcode"),{text:code,width:210,height:210});};$("copyPix").onclick=()=>navigator.clipboard.writeText($("pixCode").value);
async function buyCoinPack(id){const pack=COIN_PACKAGES.find(x=>x.id===id);if(!pack)return;if(!sb)return message("Conta indisponível","Supabase não carregou.");const{data:{session}}=await sb.auth.getSession();if(!session){message("Entre na sua conta","Faça login antes de comprar BS Coins para vincular o saldo ao seu SteamID64.");return openAuth()}let profile;try{profile=await getProfile(session.user.id)}catch(e){return message("Erro na conta",e.message)}if(!profile?.steam_id)return message("SteamID64 necessário","Sua conta precisa ter um SteamID64 cadastrado.");const tx=("BSC"+Date.now().toString().slice(-12)).slice(0,25),code=pixPayload(pack.brl,tx);const{error}=await sb.rpc("bs_create_coin_order",{p_package_id:pack.id,p_coins:pack.coins,p_amount_brl:pack.brl,p_pix_txid:tx});if(error)return message("Não foi possível criar o pedido",error.message);$("playerName").value=profile.player_name||"";$("steamId").value=profile.steam_id||"";show("checkoutModal");$("pixArea").classList.remove("hidden");$("pixCode").value=code;$("pixAmount").textContent=`${pack.coins.toLocaleString('pt-BR')} BS • PIX ${brl(pack.brl)} • ${tx}`;$("qrcode").innerHTML="";if(window.QRCode)new QRCode($("qrcode"),{text:code,width:210,height:210});$("makePix").style.display="none";message("Pedido de BS Coins criado",`Pedido de ${pack.coins.toLocaleString('pt-BR')} BS criado. Faça o PIX de ${brl(pack.brl)} e aguarde a confirmação no painel.`)}
$("checkoutBs").onclick=async()=>{if(!cart.length)return message("Carrinho vazio","Adicione produtos primeiro.");if(!sb)return message("Conta indisponível","Supabase não carregou.");const{data:{session}}=await sb.auth.getSession();if(!session)return openAuth();const items=cart.map(r=>({id:r.id,qty:r.qty}));const{data,error}=await sb.rpc("place_bs_order",{p_items:items});if(error)return message("Compra não concluída",error.message);cart=[];saveCart();closeDrawer();await refreshAccountUI();message("Compra aprovada",`Pedido #${data?.order_id||""} criado com BS Coins.`)};
document.addEventListener("DOMContentLoaded",async()=>{try{render()}catch(e){console.error(e);message("Erro ao carregar produtos",e.message)}try{await refreshAccountUI()}catch(e){console.error(e)}});