-- BRASIL SURVIVALZ V11.5 - LOJA + ADMIN INTEGRADOS
-- Execute TODO este arquivo no Supabase > SQL Editor uma única vez.

alter table public.profiles add column if not exists is_admin boolean not null default false;
alter table public.profiles add column if not exists avatar_url text;

create or replace function public.bs_is_admin() returns boolean language sql security definer set search_path=public stable as $$
 select coalesce((select is_admin from public.profiles where user_id=auth.uid() limit 1),false);
$$;
grant execute on function public.bs_is_admin() to authenticated;

create table if not exists public.bs_shop_orders(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 player_name text not null,
 steam_id text not null,
 items jsonb not null,
 total_brl numeric(10,2) not null default 0,
 total_bs bigint not null default 0,
 payment_method text not null check(payment_method in ('pix','bs')),
 pix_txid text,
 status text not null default 'pending' check(status in ('pending','approved','cancelled')),
 created_at timestamptz not null default now(),
 approved_at timestamptz,
 approved_by uuid references auth.users(id)
);
alter table public.bs_shop_orders enable row level security;

create table if not exists public.bs_coin_orders(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 package_id text not null, coins bigint not null check(coins>0), amount_brl numeric(10,2) not null check(amount_brl>0),
 pix_txid text not null unique, status text not null default 'pending' check(status in ('pending','approved','cancelled')),
 created_at timestamptz not null default now(), approved_at timestamptz, approved_by uuid references auth.users(id)
);
alter table public.bs_coin_orders enable row level security;

-- Remove assinaturas antigas para evitar erro de cache/overload no PostgREST.
drop function if exists public.bs_create_coin_order(text,integer,numeric,text);
drop function if exists public.bs_create_coin_order(text,bigint,numeric,text);
create function public.bs_create_coin_order(p_package_id text,p_coins bigint,p_amount_brl numeric,p_pix_txid text)
returns bigint language plpgsql security definer set search_path=public as $$
declare oid bigint; valid boolean;
begin
 if auth.uid() is null then raise exception 'Faça login para comprar BS Coins'; end if;
 valid := (p_package_id,p_coins,p_amount_brl) in (('bs1500',1500,15),('bs2600',2600,20),('bs3600',3600,25),('bs4600',4600,40),('bs8600',8600,80));
 if not valid then raise exception 'Pacote inválido'; end if;
 insert into public.bs_coin_orders(user_id,package_id,coins,amount_brl,pix_txid) values(auth.uid(),p_package_id,p_coins,p_amount_brl,p_pix_txid) returning id into oid;
 return oid;
end $$;
grant execute on function public.bs_create_coin_order(text,bigint,numeric,text) to authenticated;

-- Catálogo validado no servidor. Inclui TODOS os IDs da V11.5, inclusive gunrackblue.
create or replace function public.bs_catalog() returns jsonb language sql immutable as $$ select
'{"nails":{"name":"Caixa de Pregos","brl":2,"bs":650},"wire":{"name":"Arame x2","brl":5,"bs":820},"hammer":{"name":"Martelo","brl":2,"bs":550},"hatchet":{"name":"Machado Pequeno","brl":6,"bs":1200},"saw":{"name":"Serrote","brl":6,"bs":850},"stone":{"name":"Pedra de Amolar","brl":3,"bs":800},"planks":{"name":"Pack 10 Tábuas","brl":2,"bs":800},"codelock":{"name":"CodeLock","brl":15,"bs":1120},"sarka":{"name":"Sarka 120","brl":25,"bs":7000},"olga":{"name":"Olga 24","brl":25,"bs":5000},"gunter":{"name":"Gunter 2","brl":25,"bs":7000},"ada":{"name":"Ada 4x4","brl":25,"bs":9800},"m3s":{"name":"Caminhão","brl":70,"bs":12000},"kitbase":{"name":"Kit Base","brl":25,"bs":1200},"kitmedio":{"name":"Kit Médio","brl":55,"bs":10000},"kitavancado":{"name":"Kit Avançado","brl":100,"bs":15000},"vip30":{"name":"VIP Prioridade 30 dias","brl":35,"bs":15000},"gunrackblue":{"name":"Gun Rack Blue","brl":35,"bs":3500},"ta50blue":{"name":"TA-50 Locker","brl":35,"bs":4600},"gunwallwooden":{"name":"Gun Wall Wooden","brl":45,"bs":5000},"gunwallmetal":{"name":"Gun Wall Metal","brl":35,"bs":4300},"palette500":{"name":"Palette Storage 500","brl":40,"bs":12000}}'::jsonb $$;

create or replace function public.bs_build_order_items(p_items jsonb, out normalized jsonb, out total_brl numeric, out total_bs bigint)
language plpgsql security definer set search_path=public as $$
declare r jsonb; pid text; qty int; prod jsonb; arr jsonb='[]'::jsonb;
begin
 total_brl:=0; total_bs:=0;
 if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Carrinho vazio'; end if;
 for r in select * from jsonb_array_elements(p_items) loop
  pid:=r->>'id'; qty:=greatest(1,least(99,coalesce((r->>'qty')::int,1))); prod:=public.bs_catalog()->pid;
  if prod is null then raise exception 'Produto inválido: %',pid; end if;
  total_brl:=total_brl+((prod->>'brl')::numeric*qty); total_bs:=total_bs+((prod->>'bs')::bigint*qty);
  arr:=arr||jsonb_build_array(jsonb_build_object('id',pid,'name',prod->>'name','qty',qty,'brl',prod->>'brl','bs',prod->>'bs'));
 end loop; normalized:=arr;
end $$;

create or replace function public.bs_create_pix_order(p_items jsonb,p_pix_txid text)
returns bigint language plpgsql security definer set search_path=public as $$
declare pr public.profiles%rowtype; norm jsonb; brl numeric; coins bigint; oid bigint;
begin
 if auth.uid() is null then raise exception 'Faça login para finalizar'; end if;
 select * into pr from public.profiles where user_id=auth.uid(); if pr.user_id is null then raise exception 'Perfil não encontrado'; end if;
 select normalized,total_brl,total_bs into norm,brl,coins from public.bs_build_order_items(p_items);
 insert into public.bs_shop_orders(user_id,player_name,steam_id,items,total_brl,total_bs,payment_method,pix_txid,status)
 values(auth.uid(),coalesce(pr.player_name,'Jogador'),coalesce(pr.steam_id,''),norm,brl,coins,'pix',p_pix_txid,'pending') returning id into oid;
 return oid;
end $$;
grant execute on function public.bs_create_pix_order(jsonb,text) to authenticated;

create or replace function public.bs_place_bs_order(p_items jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare pr public.profiles%rowtype; norm jsonb; brl numeric; coins bigint; oid bigint; newbal bigint;
begin
 if auth.uid() is null then raise exception 'Faça login para comprar'; end if;
 select * into pr from public.profiles where user_id=auth.uid() for update; if pr.user_id is null then raise exception 'Perfil não encontrado'; end if;
 select normalized,total_brl,total_bs into norm,brl,coins from public.bs_build_order_items(p_items);
 if coalesce(pr.bs_coins,0)<coins then raise exception 'Saldo insuficiente. Necessário % BS',coins; end if;
 update public.profiles set bs_coins=bs_coins-coins where user_id=auth.uid() returning bs_coins into newbal;
 insert into public.bs_shop_orders(user_id,player_name,steam_id,items,total_brl,total_bs,payment_method,status,approved_at)
 values(auth.uid(),coalesce(pr.player_name,'Jogador'),coalesce(pr.steam_id,''),norm,brl,coins,'bs','approved',now()) returning id into oid;
 return jsonb_build_object('order_id',oid,'new_balance',newbal);
end $$;
grant execute on function public.bs_place_bs_order(jsonb) to authenticated;

create or replace function public.bs_admin_profiles() returns setof public.profiles language plpgsql security definer set search_path=public as $$ begin if not public.bs_is_admin() then raise exception 'Acesso negado'; end if; return query select * from public.profiles order by created_at desc nulls last; end $$;
grant execute on function public.bs_admin_profiles() to authenticated;

create or replace function public.bs_admin_shop_orders() returns setof jsonb language plpgsql security definer set search_path=public as $$ begin if not public.bs_is_admin() then raise exception 'Acesso negado'; end if; return query select to_jsonb(o) from public.bs_shop_orders o order by created_at desc; end $$;
grant execute on function public.bs_admin_shop_orders() to authenticated;

create or replace function public.bs_admin_coin_orders() returns setof jsonb language plpgsql security definer set search_path=public as $$ begin if not public.bs_is_admin() then raise exception 'Acesso negado'; end if; return query select to_jsonb(x) from (select c.*,p.player_name,p.steam_id from public.bs_coin_orders c left join public.profiles p on p.user_id=c.user_id order by c.created_at desc)x; end $$;
grant execute on function public.bs_admin_coin_orders() to authenticated;

create or replace function public.bs_admin_adjust_coins(p_user_id uuid,p_amount bigint,p_reason text default 'Ajuste manual') returns bigint language plpgsql security definer set search_path=public as $$ declare b bigint; begin if not public.bs_is_admin() then raise exception 'Acesso negado'; end if; update public.profiles set bs_coins=greatest(0,coalesce(bs_coins,0)+p_amount) where user_id=p_user_id returning bs_coins into b; if b is null then raise exception 'Jogador não encontrado'; end if; return b; end $$;
grant execute on function public.bs_admin_adjust_coins(uuid,bigint,text) to authenticated;

create or replace function public.bs_admin_confirm_coin_order(p_order_id bigint) returns bigint language plpgsql security definer set search_path=public as $$ declare r public.bs_coin_orders%rowtype; b bigint; begin if not public.bs_is_admin() then raise exception 'Acesso negado'; end if; select * into r from public.bs_coin_orders where id=p_order_id for update; if r.id is null then raise exception 'Pedido não encontrado'; end if; if r.status<>'pending' then raise exception 'Pedido já processado'; end if; update public.profiles set bs_coins=coalesce(bs_coins,0)+r.coins where user_id=r.user_id returning bs_coins into b; update public.bs_coin_orders set status='approved',approved_at=now(),approved_by=auth.uid() where id=p_order_id; return b; end $$;
grant execute on function public.bs_admin_confirm_coin_order(bigint) to authenticated;

-- força o PostgREST a recarregar as funções imediatamente
notify pgrst, 'reload schema';
