-- BRASIL SURVIVALZ V10.1 — execute uma vez no SQL Editor do Supabase
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  player_name text not null,
  steam_id text not null unique check (steam_id ~ '^7656119[0-9]{10}$'),
  bs_coins integer not null default 0 check (bs_coins >= 0)
);
alter table public.profiles enable row level security;
drop policy if exists "read own profile" on public.profiles;
create policy "read own profile" on public.profiles for select to authenticated using (auth.uid() = user_id);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(user_id,player_name,steam_id,bs_coins)
  values(new.id,coalesce(new.raw_user_meta_data->>'player_name','Jogador'),coalesce(new.raw_user_meta_data->>'steam_id',''),0)
  on conflict (user_id) do nothing;
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  total_bs integer not null,
  status text not null default 'paid_bs',
  created_at timestamptz not null default now()
);
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id text not null,
  qty integer not null check(qty>0),
  unit_bs integer not null
);
alter table public.orders enable row level security; alter table public.order_items enable row level security;
drop policy if exists "read own orders" on public.orders; create policy "read own orders" on public.orders for select to authenticated using(auth.uid()=user_id);
drop policy if exists "read own order items" on public.order_items; create policy "read own order items" on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));

create or replace function public.product_bs_price(pid text) returns integer language sql immutable as $$ select case pid
 when 'nails' then 180 when 'wire' then 220 when 'hammer' then 150 when 'hatchet' then 200 when 'saw' then 180 when 'stone' then 250 when 'planks' then 300 when 'codelock' then 900
 when 'sarka' then 3000 when 'olga' then 3400 when 'gunter' then 4000 when 'ada' then 4800 when 'm3s' then 7500
 when 'kitbase' then 1200 when 'kitmedio' then 2200 when 'kitavancado' then 3500 when 'vip30' then 5000
 when 'metal' then 1300 when 'weapon' then 1900 when 'grenade' then 1100 when 'equipment' then 2600 when 'ta50' then 3600 when 'rack' then 2300 else null end $$;

create or replace function public.place_bs_order(p_items jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); elem jsonb; pid text; q integer; price integer; total integer:=0; oid bigint; bal integer;
begin
 if uid is null then raise exception 'Faça login para usar BS Coins.'; end if;
 if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Carrinho vazio.'; end if;
 for elem in select * from jsonb_array_elements(p_items) loop
   pid:=elem->>'id'; q:=greatest(1,least(99,coalesce((elem->>'qty')::integer,1))); price:=product_bs_price(pid);
   if price is null then raise exception 'Produto inválido: %',pid; end if; total:=total+(price*q);
 end loop;
 select bs_coins into bal from profiles where user_id=uid for update;
 if bal is null then raise exception 'Perfil não encontrado.'; end if;
 if bal<total then raise exception 'Saldo insuficiente. Você tem % BS e precisa de % BS.',bal,total; end if;
 update profiles set bs_coins=bs_coins-total where user_id=uid;
 insert into orders(user_id,total_bs) values(uid,total) returning id into oid;
 for elem in select * from jsonb_array_elements(p_items) loop
   pid:=elem->>'id'; q:=greatest(1,least(99,coalesce((elem->>'qty')::integer,1))); price:=product_bs_price(pid);
   insert into order_items(order_id,product_id,qty,unit_bs) values(oid,pid,q,price);
 end loop;
 return jsonb_build_object('order_id',oid,'total_bs',total,'balance_after',bal-total);
end; $$;
revoke all on function public.place_bs_order(jsonb) from public; grant execute on function public.place_bs_order(jsonb) to authenticated;
