-- BRASIL SURVIVALZ V11.4 - ADMIN FINAL FIX
-- Execute no Supabase > SQL Editor.
-- Usa profiles.is_admin (a mesma coluna que a loja usa).

alter table public.profiles add column if not exists is_admin boolean not null default false;
alter table public.profiles add column if not exists avatar_url text;

create or replace function public.bs_is_admin()
returns boolean
language sql
security definer
set search_path=public
stable
as $$
  select coalesce((select p.is_admin from public.profiles p where p.user_id=auth.uid() limit 1),false);
$$;
grant execute on function public.bs_is_admin() to authenticated;

create or replace function public.bs_admin_profiles()
returns setof public.profiles
language plpgsql security definer set search_path=public
as $$
begin
 if not public.bs_is_admin() then raise exception 'Acesso negado'; end if;
 return query select * from public.profiles order by created_at desc nulls last;
end $$;
grant execute on function public.bs_admin_profiles() to authenticated;

create or replace function public.bs_admin_orders()
returns setof jsonb
language plpgsql security definer set search_path=public
as $$
begin
 if not public.bs_is_admin() then raise exception 'Acesso negado'; end if;
 return query select to_jsonb(o) from public.orders o order by o.created_at desc nulls last;
end $$;
grant execute on function public.bs_admin_orders() to authenticated;

create or replace function public.bs_admin_adjust_coins(p_user_id uuid,p_amount bigint,p_reason text default 'Ajuste manual')
returns bigint language plpgsql security definer set search_path=public
as $$
declare new_balance bigint;
begin
 if not public.bs_is_admin() then raise exception 'Acesso negado'; end if;
 update public.profiles set bs_coins=greatest(0,coalesce(bs_coins,0)+p_amount)
 where user_id=p_user_id returning bs_coins into new_balance;
 if new_balance is null then raise exception 'Jogador não encontrado'; end if;
 return new_balance;
end $$;
grant execute on function public.bs_admin_adjust_coins(uuid,bigint,text) to authenticated;

create table if not exists public.bs_coin_orders (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 package_id text not null,
 coins bigint not null check (coins > 0),
 amount_brl numeric(10,2) not null check (amount_brl > 0),
 pix_txid text not null unique,
 status text not null default 'pending' check (status in ('pending','approved','cancelled')),
 created_at timestamptz not null default now(), approved_at timestamptz, approved_by uuid references auth.users(id)
);
alter table public.bs_coin_orders enable row level security;

create or replace function public.bs_create_coin_order(p_package_id text,p_coins bigint,p_amount_brl numeric,p_pix_txid text)
returns bigint language plpgsql security definer set search_path=public
as $$
declare oid bigint; valid boolean;
begin
 if auth.uid() is null then raise exception 'Faça login para comprar BS Coins'; end if;
 valid := (p_package_id,p_coins,p_amount_brl) in (('bs1500',1500,15),('bs2600',2600,20),('bs3600',3600,25),('bs4600',4600,40),('bs8600',8600,80));
 if not valid then raise exception 'Pacote inválido'; end if;
 insert into public.bs_coin_orders(user_id,package_id,coins,amount_brl,pix_txid)
 values(auth.uid(),p_package_id,p_coins,p_amount_brl,p_pix_txid) returning id into oid;
 return oid;
end $$;
grant execute on function public.bs_create_coin_order(text,bigint,numeric,text) to authenticated;

create or replace function public.bs_admin_coin_orders()
returns setof jsonb language plpgsql security definer set search_path=public
as $$
begin
 if not public.bs_is_admin() then raise exception 'Acesso negado'; end if;
 return query select to_jsonb(x) from (
  select c.*,p.player_name,p.steam_id from public.bs_coin_orders c
  left join public.profiles p on p.user_id=c.user_id order by c.created_at desc
 ) x;
end $$;
grant execute on function public.bs_admin_coin_orders() to authenticated;

create or replace function public.bs_admin_confirm_coin_order(p_order_id bigint)
returns bigint language plpgsql security definer set search_path=public
as $$
declare r public.bs_coin_orders%rowtype; new_balance bigint;
begin
 if not public.bs_is_admin() then raise exception 'Acesso negado'; end if;
 select * into r from public.bs_coin_orders where id=p_order_id for update;
 if r.id is null then raise exception 'Pedido não encontrado'; end if;
 if r.status <> 'pending' then raise exception 'Pedido já processado'; end if;
 update public.profiles set bs_coins=coalesce(bs_coins,0)+r.coins where user_id=r.user_id returning bs_coins into new_balance;
 if new_balance is null then raise exception 'Perfil do jogador não encontrado'; end if;
 update public.bs_coin_orders set status='approved',approved_at=now(),approved_by=auth.uid() where id=p_order_id;
 return new_balance;
end $$;
grant execute on function public.bs_admin_confirm_coin_order(bigint) to authenticated;
