-- BRASIL SURVIVALZ V9 - rode UMA VEZ no SQL Editor do Supabase
create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  player_name text,
  steam_id text,
  bs_coins bigint not null default 0
);
alter table public.profiles add column if not exists user_id uuid;
create unique index if not exists profiles_user_id_key on public.profiles(user_id) where user_id is not null;
create unique index if not exists profiles_steam_id_key on public.profiles(steam_id) where steam_id is not null;

create table if not exists public.orders (
 id bigint generated by default as identity primary key,
 user_id uuid not null,
 created_at timestamptz not null default now(),
 payment_method text not null,
 status text not null default 'pending',
 total_bs bigint not null default 0,
 items jsonb not null default '[]'::jsonb
);

alter table public.profiles enable row level security;
alter table public.orders enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select to authenticated using (user_id=auth.uid());
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check (user_id=auth.uid() and bs_coins=0);
create policy "profiles_update_own" on public.profiles for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

drop policy if exists "orders_select_own" on public.orders;
create policy "orders_select_own" on public.orders for select to authenticated using (user_id=auth.uid());

revoke update on public.profiles from authenticated;
grant update(player_name,steam_id) on public.profiles to authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(user_id,player_name,steam_id,bs_coins)
  values(new.id,new.raw_user_meta_data->>'player_name',new.raw_user_meta_data->>'steam_id',0)
  on conflict (user_id) do update set player_name=excluded.player_name,steam_id=excluded.steam_id;
  return new;
end;$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.place_bs_order(p_items jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_uid uuid:=auth.uid(); v_total bigint:=0; v_balance bigint; v_order bigint; r jsonb; v_price bigint; v_qty int;
begin
  if v_uid is null then raise exception 'Faça login para usar BS Coins.'; end if;
  if jsonb_array_length(p_items)=0 then raise exception 'Carrinho vazio.'; end if;
  for r in select * from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,least(99,coalesce((r->>'qty')::int,1)));
    v_price:=case r->>'id'
      when 'nails' then 180 when 'wire' then 220 when 'hammer' then 150 when 'hatchet' then 200
      when 'saw' then 180 when 'stone' then 250 when 'planks' then 300 when 'codelock' then 900
      when 'sarka' then 3000 when 'olga' then 3400 when 'gunter' then 4000 when 'ada' then 4800 when 'm3s' then 7500
      when 'kitbase' then 1200 when 'kitmedio' then 2200 when 'kitavancado' then 3500 when 'vip30' then 5000
      when 'metal' then 1300 when 'weapon' then 1900 when 'grenade' then 1100 when 'equipment' then 2600 when 'ta50' then 3600 when 'rack' then 2300
      else null end;
    if v_price is null then raise exception 'Produto inválido: %',r->>'id'; end if;
    v_total:=v_total+(v_price*v_qty);
  end loop;
  select bs_coins into v_balance from public.profiles where user_id=v_uid for update;
  if v_balance is null then raise exception 'Perfil não encontrado.'; end if;
  if v_balance<v_total then raise exception 'Saldo insuficiente. Necessário % BS; saldo % BS.',v_total,v_balance; end if;
  update public.profiles set bs_coins=bs_coins-v_total where user_id=v_uid;
  insert into public.orders(user_id,payment_method,status,total_bs,items) values(v_uid,'bs_coins','paid',v_total,p_items) returning id into v_order;
  return jsonb_build_object('order_id',v_order,'total_bs',v_total,'remaining_bs',v_balance-v_total);
end;$$;
revoke all on function public.place_bs_order(jsonb) from public;
grant execute on function public.place_bs_order(jsonb) to authenticated;
