const SUPABASE_URL="https://itoxohdbwcxmrlxqfkct.supabase.co";const SUPABASE_KEY="sb_publishable_Enj8kwWvvtHNUCBva-uPHg_incNY4jK";const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=x=>document.getElementById(x);let profiles=[],orders=[],coinOrders=[];
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function isAdmin(){
 const {data:{session}}=await sb.auth.getSession();
 if(!session)return false;
 const {data,error}=await sb.from('profiles').select('is_admin').eq('user_id',session.user.id).maybeSingle();
 if(error){console.error('admin check',error);return false}
 return data?.is_admin===true;
}
async function boot(){if(await isAdmin()){$('login').classList.add('hidden');$('app').classList.remove('hidden');loadAll()}else{$('app').classList.add('hidden');$('login').classList.remove('hidden')}}
$('enter').onclick=async()=>{$('loginMsg').textContent='Entrando...';const {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('loginMsg').textContent='E-mail ou senha incorretos.';return}if(!(await isAdmin())){await sb.auth.signOut();$('loginMsg').textContent='Esta conta não tem permissão de administrador.';return}$('loginMsg').textContent='';boot()};$('logout').onclick=async()=>{await sb.auth.signOut();boot()};
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$(id).classList.add('active');$('pageTitle').textContent={dashboard:'Dashboard',players:'Jogadores',orders:'Pedidos',coins:'BS Coins',vip:'VIP',products:'Produtos / MMG',coinorders:'Compras BS / PIX'}[id]||id}
function table(rows,cols){if(!rows.length)return '<p class="muted">Nenhum registro encontrado.</p>';return '<div class="tableWrap"><table><thead><tr>'+cols.map(c=>`<th>${c[0]}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>`<td>${esc(typeof c[1]==='function'?c[1](r):r[c[1]])}</td>`).join('')+'</tr>').join('')+'</tbody></table></div>'}
async function loadProfiles(){const {data,error}=await sb.rpc('bs_admin_profiles');profiles=data||[];if(error)console.error(error);drawProfiles()}
function drawProfiles(){const q=($('playerSearch')?.value||'').toLowerCase();const r=profiles.filter(p=>!q||String(p.player_name||'').toLowerCase().includes(q)||String(p.steam_id||'').includes(q));$('playersTable').innerHTML=table(r,[['JOGADOR','player_name'],['STEAMID64','steam_id'],['BS COINS',x=>Number(x.bs_coins||0).toLocaleString('pt-BR')+' BS'],['CRIADO',x=>x.created_at?new Date(x.created_at).toLocaleString('pt-BR'):'—']]);$('coinTable').innerHTML=table(profiles,[['JOGADOR','player_name'],['STEAMID64','steam_id'],['SALDO',x=>Number(x.bs_coins||0).toLocaleString('pt-BR')+' BS']]);$('coinPlayer').innerHTML='<option value="">Selecione um jogador</option>'+profiles.map(p=>`<option value="${esc(p.user_id)}">${esc(p.player_name||p.steam_id)} — ${esc(p.steam_id||'')}</option>`).join('')}
$('playerSearch').oninput=drawProfiles;
async function loadOrders(){const {data,error}=await sb.rpc('bs_admin_orders');orders=data||[];if(error)console.error(error);const cols=[['ID',x=>x.id||'—'],['JOGADOR',x=>x.player_name||'—'],['STEAMID64',x=>x.steam_id||'—'],['VALOR',x=>x.total_brl!=null?'R$ '+Number(x.total_brl).toFixed(2).replace('.',','):'—'],['BS',x=>x.total_bs!=null?Number(x.total_bs).toLocaleString('pt-BR')+' BS':'—'],['STATUS',x=>x.status||'—'],['DATA',x=>x.created_at?new Date(x.created_at).toLocaleString('pt-BR'):'—']];$('ordersTable').innerHTML=table(orders,cols);$('recentOrders').innerHTML=table(orders.slice(0,6),cols.slice(0,6));$('vipOrders').innerHTML=table(orders.filter(o=>JSON.stringify(o).toLowerCase().includes('vip')),cols)}
$('applyCoins').onclick=async()=>{const uid=$('coinPlayer').value,amount=Number($('coinAmount').value),reason=$('coinReason').value.trim();if(!uid||!Number.isFinite(amount)||amount===0){$('coinMsg').textContent='Selecione o jogador e informe um valor diferente de zero.';return}const {data,error}=await sb.rpc('bs_admin_adjust_coins',{p_user_id:uid,p_amount:amount,p_reason:reason||'Ajuste manual'});$('coinMsg').textContent=error?error.message:`Saldo atualizado: ${Number(data||0).toLocaleString('pt-BR')} BS`;if(!error){$('coinAmount').value='';$('coinReason').value='';await loadProfiles()}}
const catalog=[['Caixa de Pregos','../nails.jpg','R$ 2,00 • 650 BS'],['Arame x2','../wire.jpg','R$ 5,00 • 820 BS'],['Martelo','../hammer.jpg','R$ 2,00 • 550 BS'],['Machado Pequeno','../hatchet.jpg','R$ 6,00 • 1.200 BS'],['Serrote','../handsaw.jpg','R$ 6,00 • 850 BS'],['Pedra de Amolar','../sharpening_stone.jpg','R$ 3,00 • 800 BS'],['Pack 10 Tábuas','../planks.jpg','R$ 2,00 • 800 BS'],['CodeLock','../codlock.jpg','R$ 15,00 • 1.120 BS'],['Sarka 120','../sarka.jpg','R$ 25,00 • 7.000 BS'],['Olga 24','../olga.jpg','R$ 25,00 • 5.000 BS'],['Gunter 2','../gunter.jpg','R$ 25,00 • 7.000 BS'],['Ada 4x4','../ada.jpg','R$ 25,00 • 9.800 BS'],['Caminhão','../m3s.jpg','R$ 70,00 • 12.000 BS'],['Kit Base','../kit_base.jpg','R$ 25,00 • 1.200 BS'],['Kit Médio','../kit_medio.jpg','R$ 55,00 • 10.000 BS'],['Kit Avançado','../kit_avancado.jpg','R$ 100,00 • 15.000 BS'],['VIP Prioridade','../vip.jpg','R$ 35,00 • 15.000 BS'],['Gun Rack Blue','../mmg_gun_rack_blue.jpg','R$ 35,00 • 3.500 BS'],['TA-50 Locker','../mmg_ta50_locker_blue.jpg','R$ 35,00 • 4.600 BS'],['Gun Wall Wooden','../mmg_gun_wall_wooden.jpg','R$ 45,00 • 5.000 BS'],['Gun Wall Metal','../mmg_gun_wall_metal.jpg','R$ 35,00 • 4.300 BS'],['Palette Storage 500','../mmg_palette_storage_500.jpg','R$ 40,00 • 12.000 BS']];$('catalog').innerHTML=catalog.map(x=>`<article class="prod"><img src="${x[1]}"><div><b>${x[0]}</b><small>Catálogo atual</small><em>${x[2]}</em></div></article>`).join('');
async function loadCoinOrders(){
 const {data,error}=await sb.rpc('bs_admin_coin_orders'); coinOrders=data||[];
 if(error){console.error(error);$('coinOrdersTable').innerHTML='<p class="muted">Execute o SUPABASE_ADMIN_SETUP.sql atualizado para ativar esta área.</p>';return}
 if(!coinOrders.length){$('coinOrdersTable').innerHTML='<p class="muted">Nenhuma compra de BS Coins registrada.</p>';return}
 $('coinOrdersTable').innerHTML='<div class="tableWrap"><table><thead><tr><th>ID</th><th>JOGADOR</th><th>STEAMID64</th><th>PACOTE</th><th>PIX</th><th>STATUS</th><th>AÇÃO</th></tr></thead><tbody>'+coinOrders.map(o=>'<tr><td>#'+o.id+'</td><td>'+esc(o.player_name||'—')+'</td><td>'+esc(o.steam_id||'—')+'</td><td>'+Number(o.coins).toLocaleString('pt-BR')+' BS</td><td>R$ '+Number(o.amount_brl).toFixed(2).replace('.',',')+'</td><td>'+esc(o.status)+'</td><td>'+(o.status==='pending'?'<button onclick="confirmCoinOrder('+o.id+')">CONFIRMAR PIX</button>':'—')+'</td></tr>').join('')+'</tbody></table></div>';
}
async function confirmCoinOrder(id){
 if(!confirm('Você conferiu o PIX e quer adicionar os BS Coins à conta deste jogador?'))return;
 const {data,error}=await sb.rpc('bs_admin_confirm_coin_order',{p_order_id:id});
 if(error)return alert(error.message);
 alert('Pagamento confirmado. Novo saldo: '+Number(data).toLocaleString('pt-BR')+' BS');
 await Promise.all([loadCoinOrders(),loadProfiles()]);
}
window.loadCoinOrders=loadCoinOrders; window.confirmCoinOrder=confirmCoinOrder;

async function loadAll(){await Promise.all([loadProfiles(),loadOrders(),loadCoinOrders()]);$('statPlayers').textContent=profiles.length;$('statOrders').textContent=orders.length;$('statPending').textContent=orders.filter(o=>String(o.status||'').toLowerCase().includes('pend')).length;$('statCoins').textContent=profiles.reduce((s,p)=>s+Number(p.bs_coins||0),0).toLocaleString('pt-BR')+' BS'}window.loadAll=loadAll;window.loadOrders=loadOrders;boot();
